swagger: '2.0'
info:
  description: |
    This is the backend for the pulu project.
    [http://swagger.io](http://swagger.io) or on 
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: Pulu Backend
  
tags:
- name: sensors
  description: Everything about sensors
  externalDocs:
    description: Find out more
    url: http://swagger.io

paths:
  /sensors:
    get:
      tags:
        - sensors
      summary: List all sensors
      responses:
        200:
          description: succesful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Sensor'
    post:
      tags:
        - sensors
      summary: Create new sensor
      parameters:
        - in: body
          name: body
          description: Sensor object that needs to be added to the database
          required: true
          schema:
            $ref: '#/definitions/SensorBody'
      responses:
        201:
          description: succesful operation
          schema:
            $ref: '#/definitions/Sensor'
          
  /sensors/{sensorId}:
    get:
      tags:
        - sensors
      summary: Find a sensor by ID
      operationId: getSensorById
      produces:
        - application/json
      parameters:
        - in: path 
          name: sensorId
          description: ID of device to return
          required: true
          type: string
        - name: time
          in: query
          description: specify time until first to last value
          type: array
          items:
            type: string
            enum:
            - last
            - hour
            - day
            - week
            - year
            - all
            default: last
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/SensorValue'
        400:
          description: Invalid ID supplied
        404:
          description: Sensor not found
    put:
      tags:
      - sensors
      summary: Update an existing sensor
      operationId: updateSensor
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: sensorId
          description: ID of sensor to return
          required: true
          type: string
        - in: body
          name: body
          description: Sensor object that update the existing sensor
          required: true
          schema:
            $ref: '#/definitions/SensorBody'
      responses:
        204:
          description: Succesful operation
        400:
          description: Invalid ID supplied
        404:
          description: Sensor not found
        405:
          description: Validation exception
    delete:
      tags:
      - sensors
      summary: Deletes a sensor
      operationId: deleteSensor
      produces:
      - application/json
      - application/xml
      parameters:
        - name: sensorId
          in: path
          description: ID of sensor to return
          required: true
          type: string
      responses:
        204:
          description: Succesful operation
        400:
          description: Invalid ID supplied
        404:
          description: Sensor not found
          
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    required:
      - _id
      - username
      - password
    properties:
      _id:
        type: string
      username:
        type: string
      password:
        type: string
  Sensor:
    type: object
    required:
    - _id
    - firstname
    - lastname
    - deviceid
    - devicename
    - location
    properties:
      _id:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      deviceid:
        type: string
      devicename:
        type: string
      location:
        type: object
        properties:
          lat:
            type: number
          long:
            type: number
  SensorValue:
    type: object
    required:
    - _id
    - firstname
    - lastname
    - deviceid
    - devicename
    - location
    properties:
      _id:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      deviceid:
        type: string
      devicename:
        type: string
      location:
        type: object
        properties:
          lat:
            type: number
          long:
            type: number
      values:
        type: array
        items:
          type: object
          properties:
            battery:
              type: number
            light:
              type: number
            moisture:
              type: object
              properties:
                level1:
                  type: number
                level2:
                  type: number
                level3:
                  type: number
                level4:
                  type: number
            temperature:
              type: object
              properties:
                air:
                  type: number
                ground:
                  type: number
  ApiResponse:
    type: object
    properties:
      message:
        type: string
  SensorBody:
    type: object
    required:
    - firstname
    - lastname
    - deviceid
    - devicename
    - location
    properties:
      firstname:
        type: string
      lastname:
        type: string
      deviceid:
        type: string
      devicename:
        type: string
      location:
        type: object
        properties:
          lat:
            type: number
          long:
            type: number
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /p9138/Pulu-Backend/1.0.0
schemes:
 - https
 - http