swagger: '2.0'
info:
  description: |
    This is the backend for the pulu project, you can find it on [GitHub](https://github.com/vives-projectwerk-2021/pulu-backend).
  version: 1.0.0
  title: Pulu Backend
tags:
  - name: sensors
    description: Everything about sensors
  - name: livedata
    description: Getting live data from sensors
  - name: metrics
    description: Devops metrics
paths:
  /sensors:
    get:
      tags:
        - sensors
      summary: List all sensors
      responses:
        '200':
          description: succesful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Sensor'
    post:
      tags:
        - sensors
      summary: Create new sensor
      parameters:
        - in: body
          name: body
          description: Sensor object that needs to be added to the database
          required: true
          schema:
            $ref: '#/definitions/Sensor'
      responses:
        '201':
          description: succesful operation
          schema:
            $ref: '#/definitions/Sensor'
  /sensors/{sensorId}:
    get:
      tags:
        - sensors
      summary: Find a sensor by ID
      operationId: getSensorById
      produces:
        - application/json
      parameters:
        - name: sensorId
          in: path
          description: ID of device to return
          required: true
          type: string
        - name: start
          in: query
          description: 'start time - Example: 2018-03-20T09:12:28Z'
          type: string
          format: date-time
        - name: stop
          in: query
          description: 'stop time - Example: 2018-03-20T09:12:28Z'
          type: string
          format: date-time
        - name: step
          in: query
          description: specify time until first to last value
          type: array
          items:
            type: string
            enum:
              - hour
              - day
              - week
              - year
              - all
            default: hour
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SensorValue'
        '400':
          description: Invalid ID supplied
        '404':
          description: Sensor not found
    put:
      tags:
        - sensors
      summary: Update an existing sensor
      operationId: updateSensor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: sensorId
          description: ID of sensor to return
          required: true
          type: string
        - in: body
          name: body
          description: Sensor object that update the existing sensor
          required: true
          schema:
            $ref: '#/definitions/SensorBody'
      responses:
        '204':
          description: Succesful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Sensor not found
        '405':
          description: Validation exception
    delete:
      tags:
        - sensors
      summary: Deletes a sensor
      operationId: deleteSensor
      produces:
        - application/json
        - application/xml
      parameters:
        - name: sensorId
          in: path
          description: ID of sensor to return
          required: true
          type: string
      responses:
        '204':
          description: Succesful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Sensor not found
  /livedata:
    get:
      tags:
        - livedata
    post:
      tags:
        - livedata
  /metrics:
    get:
      tags:
        - metrics
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    required:
      - _id
      - username
      - password
    properties:
      _id:
        type: string
      username:
        type: string
      password:
        type: string
  Sensor:
    type: object
    required:
      - deviceid
      - devicename
      - location
    properties:
      deviceid:
        type: string
      devicename:
        type: string
      location:
        type: object
        required:
          - lat
          - long
          - place_name
        properties:
          lat:
            type: number
          long:
            type: number
          place_name:
            type: string
  livedata:
    type: object
    properties:
      message:
        type: string
      data:
        type: object
        properties:
          device_id:
            type: string
          time:
            type: string
          count:
            type: number
          sensors:
            type: object
            properties:
              voltage:
                type: object
                properties:
                  battery:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
              light:
                type: object
                properties:
                  status:
                    type: number
                  value:
                    type: number
              moisture:
                type: object
                properties:
                  level1:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
                  level2:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
                  level3:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
                  level4:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
              temperature:
                type: object
                properties:
                  air:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
                  ground:
                    type: object
                    properties:
                      status:
                        type: number
                      value:
                        type: number
          meta:
            type: object
            properties:
              gateway_cnt:
                type: number
              strongest_rssi:
                type: number
              strongest_gateway:
                type: string
  SensorValue:
    type: object
    required:
      - info
    properties:
      info:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          lastseen:
            type: string
            format: date-time
          location:
            type: object
            properties:
              lat:
                type: number
              long:
                type: number
              place_name:
                type: string
      value:
        type: array
        items:
          type: object
          properties:
            result:
              type: string
            table:
              type: number
            _start:
              type: string
              format: date-time
            _stop:
              type: string
              format: date-time
            _time:
              type: string
              format: date-time
            _value:
              type: number
            _field:
              type: string
            _measurement:
              type: string
            host:
              type: string
            moisture:
              type: string
  ErrorResponse:
    type: object
    required:
      - status
      - message
      - timestamp
    properties:
      status:
        type: number
      message:
        type: string
      timestamp:
        type: string
        format: date-time
      details:
        type: string
  SensorBody:
    type: object
    required:
      - devicename
      - location
    properties:
      devicename:
        type: string
      location:
        type: object
        required:
          - lat
          - long
          - place_name
        properties:
          lat:
            type: number
          long:
            type: number
          place_name:
            type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
host: virtserver.swaggerhub.com
basePath: /p9138/Pulu-Backend/1.0.0
schemes:
  - https
  - http
